TESTS = {
    '1': lambda x, y, z: x > y > z,
    '2': lambda x, y, z: x >= y >= z,
    '3': lambda x, y, z: x < y < z,
    '4': lambda x, y, z: y > x and y > z,
    '5': lambda x, y, z: y < x and y < z,
    '6': lambda x, y, z: abs(x) > abs(y) > abs(z),
    '7': lambda x, y, z: (x % 2 == 0) and (y % 2 == 0) and (z % 2 == 0),
    '8': lambda x, y, z: (x % 2 == 1) and (y % 2 == 1) and (z % 2 == 1),
    '9': lambda x, y, z: x == y and y == z,
    '10': lambda x, y, z: x != y and y != z and x != z,
    '11': lambda x, y, z: x + y > z,
    '12': lambda x, y, z: x * y < z,
    '13': lambda x, y, z: x ** 2 + y ** 2 == z ** 2,
    '14': lambda x, y, z: x > 0 and y > 0 and z > 0,
    '15': lambda x, y, z: x < 0 and y < 0 and z < 0,
    '16': lambda x, y, z: x * y * z > 0,
    '17': lambda x, y, z: x * y * z < 0,
    '18': lambda x, y, z: max(x, y, z) == x,
    '19': lambda x, y, z: min(x, y, z) == z,
    '20': lambda x, y, z: (x + y + z) % 3 == 0,
    '21': lambda x, y, z: x % 2 == 0 and y % 2 == 1 and z % 2 == 0,
    '22': lambda x, y, z: abs(x - y) < abs(y - z),
    '23': lambda x, y, z: x > y > 0 > z,
    '24': lambda x, y, z: x < 0 < y < z,
    '25': lambda x, y, z: x ** 2 > y ** 2 > z ** 2,
    '26': lambda x, y, z: x + y == z,
    '27': lambda x, y, z: x - y == z,
    '28': lambda x, y, z: x * y == z,
    '29': lambda x, y, z: x / y == z if y != 0 else False,
    '30': lambda x, y, z: x % y == z if y != 0 else False,
    '31': lambda x, y, z: abs(x) + abs(y) > abs(z),
    '32': lambda x, y, z: x > y > z > 0,
    '33': lambda x, y, z: 0 > x > y > z,
    '34': lambda x, y, z: x > 0 > y > z,
    '35': lambda x, y, z: x > y > 0 > z,
    '36': lambda x, y, z: (x + y) / 2 == z,
    '37': lambda x, y, z: x ** 2 + y ** 2 > z ** 2,
    '38': lambda x, y, z: x ** 2 + y ** 2 < z ** 2,
    '39': lambda x, y, z: x % 3 == 0 and y % 3 == 1 and z % 3 == 2,
    '40': lambda x, y, z: x >= 0 and y >= 0 and z < 0,
    '41': lambda x, y, z: x < 0 and y >= 0 and z >= 0,
    '42': lambda x, y, z: abs(x - y) == abs(y - z),
    '43': lambda x, y, z: x * y > 0 and y * z < 0,
    '44': lambda x, y, z: x ** 3 > y ** 2 > z,
    '45': lambda x, y, z: x > y ** 2 and y > z ** 2,
    '46': lambda x, y, z: x ** 0.5 > y > z ** 2 if x >= 0 else False,
    '47': lambda x, y, z: x + y > y + z > z + x,
    '48': lambda x, y, z: x * y > y * z > z * x,
    '49': lambda x, y, z: x % 10 == y % 10 == z % 10,
    '50': lambda x, y, z: int(x) == x and int(y) == y and int(z) != z,
    '51': lambda x, y, z: x > y > z and x < y + z,
    '52': lambda x, y, z: x < y < z and x > y - z,
    '53': lambda x, y, z: abs(x) % 2 == 0 and abs(y) % 2 == 1 and abs(z) % 2 == 0,
    '54': lambda x, y, z: x > 0 and y < 0 and z > 0,
    '55': lambda x, y, z: x < 0 and y > 0 and z < 0,
    '56': lambda x, y, z: max(x, y, z) - min(x, y, z) == sum([x, y, z]) - max(x, y, z) - min(x, y, z),
    '57': lambda x, y, z: x ** 2 + y ** 2 + z ** 2 < (x + y + z) ** 2,
    '58': lambda x, y, z: x ** 2 + y ** 2 + z ** 2 > (x + y + z) ** 2,
    '59': lambda x, y, z: x * y * z == (x + y + z) ** 2,
    '60': lambda x, y, z: x ** 2 - y ** 2 == z ** 2,
    '61': lambda x, y, z: abs(x - y) + abs(y - z) == abs(x - z),
    '62': lambda x, y, z: x * y * z == x + y + z,
    '63': lambda x, y, z: x ** y > z if y >= 0 else False,
    '64': lambda x, y, z: x < y < z < x + y,
    '65': lambda x, y, z: x > y > z > x - y,
    '66': lambda x, y, z: x % 4 == 0 and y % 4 == 1 and z % 4 == 2,
    '67': lambda x, y, z: abs(x + y + z) < max(abs(x), abs(y), abs(z)),
    '68': lambda x, y, z: abs(x + y + z) > max(abs(x), abs(y), abs(z)),
    '69': lambda x, y, z: (x > 0 and y < 0 and z > 0) or (x < 0 and y > 0 and z < 0),
    '70': lambda x, y, z: x ** 2 > y ** 3 > z ** 4 if y >= 0 and z >= 0 else False,
    '71': lambda x, y, z: x + y > z and x + z > y and y + z > x,
    '72': lambda x, y, z: x ** 2 + y ** 2 + z ** 2 == (x + y + z) ** 2,
    '73': lambda x, y, z: x * y * z < x + y + z,
    '74': lambda x, y, z: x * y * z > x + y + z,
    '75': lambda x, y, z: abs(x - y) * abs(y - z) == abs(x - z),
    '76': lambda x, y, z: (x > y and y > z) or (x < y and y < z),
    '77': lambda x, y, z: (x >= 0 and y < 0) or (x < 0 and y >= 0),
    '78': lambda x, y, z: (x % 5 == 0) and (y % 5 == 0) and (z % 5 != 0),
    '79': lambda x, y, z: (x < -50 and y > -50 and y < 50 and z > 50) or (x > 50 and y > -50 and y < 50 and z < -50),
    '80': lambda x, y, z: x ** 2 + y ** 2 + z ** 2 < 100,
    '81': lambda x, y, z: x ** 2 + y ** 2 + z ** 2 > 10000,
    '82': lambda x, y, z: (x > 0 and y > 0 and z < 0) or (x < 0 and y < 0 and z > 0),
    '83': lambda x, y, z: abs(x) + abs(y) + abs(z) < 10,
    '84': lambda x, y, z: abs(x) + abs(y) + abs(z) > 200,
    '85': lambda x, y, z: x * y * z == 0 and x + y + z != 0,
    '86': lambda x, y, z: (x > y > 0 and z < 0) or (x < y < 0 and z > 0),
    '87': lambda x, y, z: abs(x - y) > abs(y - z) > abs(x - z),
    '88': lambda x, y, z: (x + y + z) ** 2 > x ** 2 + y ** 2 + z ** 2,
    '89': lambda x, y, z: (x + y + z) ** 2 < x ** 2 + y ** 2 + z ** 2,
    '90': lambda x, y, z: x % 7 == 0 and y % 7 == 0 and z % 7 != 0,
    '91': lambda x, y, z: (x > 0 and y < 0 and z == 0) or (x < 0 and y > 0 and z == 0),
    '92': lambda x, y, z: abs(x) > 50 and abs(y) < 50 and abs(z) > 50,
    '93': lambda x, y, z: x + y + z > 100 or x + y + z < -100,
    '94': lambda x, y, z: -10 < x < 10 and -10 < y < 10 and -10 < z < 10,
    '95': lambda x, y, z: x * y > 0 > y * z,
    '96': lambda x, y, z: (x > y and y < z) or (x < y and y > z),
    '97': lambda x, y, z: (x % 3 == 0) and (y % 3 == 1) and (z % 3 == 2),
    '98': lambda x, y, z: (x > 0 and y < 0) or (x < 0 and y > 0) or (y > 0 and z < 0) or (y < 0 and z > 0),
    '99': lambda x, y, z: abs(x) + abs(y) == abs(z),
    '100': lambda x, y, z: (x ** 2 + y ** 2 + z ** 2) % 2 == 0,
}
